### ISSUE TITLE
Don't require `GITHUB_TOKEN` when it is not needed

### ISSUE THREAD

**Issue by rajbos** [UlisesGascon/openssf-scorecard-monitor#47]
From what I can see, the `GITHUB_TOKEN` is not needed for discovery (it would only have access to the current repo anyway), so we can remove it from [this check](https://github.com/UlisesGascon/openssf-scorecard-monitor/blob/main/src/action.js#L36). I ran into it during debugging (output tested in a ACTIONS_STEP_SUMMARY) and since it is not needed....

**Comment by UlisesGascon** [comment]
I think we need it for the discovery mode because in order to use the `octokit` instance ([See](https://github.com/UlisesGascon/openssf-scorecard-monitor/blob/main/src/index.js#L20)) you first need to provide the token ([See](https://github.com/UlisesGascon/openssf-scorecard-monitor/blob/main/src/action.js#L45))

**Comment by rajbos** [comment]
For the call to get public repos you don't need to be authenticate, so that was my thinking. I now remember that this will work on github.com, but not on Enterprise server (where I eventually want to use this as well for my customers), since even for a public repo on that, you will need to be authenticated. 

Even the Octokit toolkit makes the token required, so it is needed. 

Good to double check this indeed 😄. Closing this issue.
